import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'react-hot-toast';


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}

 

<Toaster
    position="bottom-center"
    toastOptions={{
        duration: 3500,

        style: {
            background: '#1f2937',
            color: '#fff',
            padding: '12px 18px',
            borderRadius: '10px',
            fontSize: '14px',
            fontWeight: 500,
            boxShadow:
                '0 8px 24px rgba(0, 0, 0, 0.18)',
        },

        success: {
            iconTheme: {
                primary: '#22c55e',
                secondary: '#fff',
            },
        },

        error: {
            iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
            },
        },
    }}
/>
 

      </body>
    </html>
  );
}
